---
- name: To install docker on remote servers
  hosts: test
  tasks:
    - name: Installing docker
      yum:
        name: docker
        state: present
      notify: service restart

  handlers:
    - name: service restart

      service:
        name: docker
        state: started
        enabled: true

